# Generated by Django 4.1.3 on 2022-11-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='listings',
        ),
    ]
