# Generated by Django 4.1.2 on 2022-11-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_delete_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='movie_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
